# Generated by Django 3.0.7 on 2020-08-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_auto_20200816_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isApprove',
            field=models.BooleanField(default=False),
        ),
    ]
