# Generated by Django 3.0.7 on 2020-08-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_comment_isapprove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
