# Generated by Django 3.0.7 on 2020-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0010_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.CharField(default='3 min', max_length=10),
        ),
    ]
