# Generated by Django 3.0.7 on 2020-09-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0011_auto_20200901_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='tags',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
