# Generated by Django 3.0.7 on 2020-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0012_auto_20200901_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('problem', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
