# Generated by Django 3.0.7 on 2020-10-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0013_auto_20201010_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
