# Generated by Django 3.0.7 on 2020-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0014_auto_20201010_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subsriber_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
