# Generated by Django 3.0.7 on 2020-10-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0015_subsriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
