# Generated by Django 3.0.7 on 2020-10-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0018_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
