# Generated by Django 3.0.7 on 2020-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0019_contact_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image'),
        ),
    ]
