# Generated by Django 3.0.7 on 2020-12-06 13:18

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0020_auto_20201206_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='featured_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='featured_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='featured_image'),
        ),
    ]
