# Generated by Django 3.0.7 on 2020-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0023_auto_20201211_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='authorId',
            field=models.CharField(default=None, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='draft',
            name='tags',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='draft',
            name='title',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='authorId',
            field=models.CharField(default=None, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
