# Generated by Django 3.0.7 on 2020-12-22 12:09

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0024_auto_20201220_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='body',
            field=django_editorjs.fields.EditorJsField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
